/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LimoService } from "../limo.service";
import { LimoCreateInput } from "./LimoCreateInput";
import { Limo } from "./Limo";
import { LimoFindManyArgs } from "./LimoFindManyArgs";
import { LimoWhereUniqueInput } from "./LimoWhereUniqueInput";
import { LimoUpdateInput } from "./LimoUpdateInput";
import { ReservationFindManyArgs } from "../../reservation/base/ReservationFindManyArgs";
import { Reservation } from "../../reservation/base/Reservation";
import { ReservationWhereUniqueInput } from "../../reservation/base/ReservationWhereUniqueInput";

export class LimoControllerBase {
  constructor(protected readonly service: LimoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Limo })
  async createLimo(@common.Body() data: LimoCreateInput): Promise<Limo> {
    return await this.service.createLimo({
      data: data,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        licensePlate: true,
        make: true,
        model: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Limo] })
  @ApiNestedQuery(LimoFindManyArgs)
  async limos(@common.Req() request: Request): Promise<Limo[]> {
    const args = plainToClass(LimoFindManyArgs, request.query);
    return this.service.limos({
      ...args,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        licensePlate: true,
        make: true,
        model: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Limo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async limo(
    @common.Param() params: LimoWhereUniqueInput
  ): Promise<Limo | null> {
    const result = await this.service.limo({
      where: params,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        licensePlate: true,
        make: true,
        model: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Limo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLimo(
    @common.Param() params: LimoWhereUniqueInput,
    @common.Body() data: LimoUpdateInput
  ): Promise<Limo | null> {
    try {
      return await this.service.updateLimo({
        where: params,
        data: data,
        select: {
          capacity: true,
          createdAt: true,
          id: true,
          licensePlate: true,
          make: true,
          model: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Limo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLimo(
    @common.Param() params: LimoWhereUniqueInput
  ): Promise<Limo | null> {
    try {
      return await this.service.deleteLimo({
        where: params,
        select: {
          capacity: true,
          createdAt: true,
          id: true,
          licensePlate: true,
          make: true,
          model: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/reservations")
  @ApiNestedQuery(ReservationFindManyArgs)
  async findReservations(
    @common.Req() request: Request,
    @common.Param() params: LimoWhereUniqueInput
  ): Promise<Reservation[]> {
    const query = plainToClass(ReservationFindManyArgs, request.query);
    const results = await this.service.findReservations(params.id, {
      ...query,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,

        driver: {
          select: {
            id: true,
          },
        },

        dropoffLocation: true,
        id: true,

        limo: {
          select: {
            id: true,
          },
        },

        pickupLocation: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reservations")
  async connectReservations(
    @common.Param() params: LimoWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        connect: body,
      },
    };
    await this.service.updateLimo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reservations")
  async updateReservations(
    @common.Param() params: LimoWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        set: body,
      },
    };
    await this.service.updateLimo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reservations")
  async disconnectReservations(
    @common.Param() params: LimoWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        disconnect: body,
      },
    };
    await this.service.updateLimo({
      where: params,
      data,
      select: { id: true },
    });
  }
}
